spring:
  application:
    name: api-gateway
  profiles:
    active: dev

  config:
    import: configserver:http://localhost:8888


# JWT Configuration - AGREGAR ESTA SECCIÓN
jwt:
  secret: tuClaveSecretaSuperSegura123456789